version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"  # 호스트의 80번 포트를 컨테이너의 80번 포트에 매핑
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Nginx 설정 파일 마운트
      - ./html:/usr/share/nginx/html  # 정적 웹 파일(HTML) 저장 경로
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
